name: Python CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest flake8 bandit  # Install testing and scanning tools

      # Step 4: Run Pytest (unit tests)
      - name: Run tests with pytest
        run: |
          pytest --maxfail=5 --disable-warnings  # Run pytest with max fail set to 5

      # Step 5: Static Code Analysis with Flake8
      - name: Run Flake8 (Static Code Analysis)
        run: |
          flake8 code/ --max-line-length=120  # Flake8 to lint the code directory

      # Step 6: Security Scanning with Bandit
      - name: Run Bandit (Security Scanning)
        run: |
          bandit -r code/  # Recursively scan the code directory for security issues

