on:
  schedule:
    - cron: '*/15 * * * *'  # Run every 15 minutes
  push:
    branches:
      - main
      - development

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest flake8 bandit

      - name: Run Tests
        run: |
          coverage run -m pytest test/
          coverage report
          exit_code=$?
          if [ $exit_code -eq 0 ]; then
            echo "COVERAGE_STATUS=Pass" >> $GITHUB_ENV
          else
            echo "COVERAGE_STATUS=Fail" >> $GITHUB_ENV
          fi

      - name: Create Coverage Badge
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: f90d8ff63781978b73c28561177358b3
          filename: coverage.json
          label: Coverage
          message: ${{ env.COVERAGE_STATUS }}
          color: ${{ env.COVERAGE_STATUS == 'Pass' && 'green' || 'red' }}
        continue-on-error: true

      - name: Run Flake8 (Static Code Analysis)
        run: |
          flake8 code/ --max-line-length=120
          exit_code=$?
          if [ $exit_code -eq 0 ]; then
            echo "STATIC_CODE_STATUS=Pass" >> $GITHUB_ENV
          else
            echo "STATIC_CODE_STATUS=Fail" >> $GITHUB_ENV
          fi
        continue-on-error: true  # Allow the workflow to continue even if this step fails

      - name: Create Static Code Analysis Badge
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 6e6740fb4d21afa29af5a1eba71cedba
          filename: Static_code_analysis.json
          label: Static Code Analysis
          message: ${{ env.STATIC_CODE_STATUS }}
          color: ${{ env.STATIC_CODE_STATUS == 'Pass' && 'green' || 'red' }}
        continue-on-error: true  # This will ensure the badge is created even if Flake8 fails

      - name: Run Bandit (Security Scanning)
        run: |
          bandit -r code/
          exit_code=$?
          if [ $exit_code -eq 0 ]; then
            echo "SECURITY_STATUS=Pass" >> $GITHUB_ENV
          else
            echo "SECURITY_STATUS=Fail" >> $GITHUB_ENV
          fi
        continue-on-error: true  # Continue even if Bandit fails

      - name: Create Security Scan Badge
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: e9d969e042f2cc3e639dbac2a074ba92
          filename: Security_scan.json
          label: Security Scan
          message: ${{ env.SECURITY_STATUS }}
          color: ${{ env.SECURITY_STATUS == 'Pass' && 'green' || 'red' }}
        continue-on-error: true 
